export var RABBITS = [
  {
    name: "Akua",
    image: "css/rabbitAssets/rabbitImages/Akua.png",
    breed: "Drawf Mix",
    sex: "Female",
    age: "8 Months",
    weight: "4 Pounds",
    bio: "I'm Akua and I'm new here! I was found running loose for at least a month, it was cold out and hard to find food! I'm happy to be a house rabbit now. <br>  <br>I am a very sweet bunny and very curious. I love my run time! My foster family says I can be shy at first and may take a little more time warming up to a person. Once I warm up, I want attention and enjoy being petted!",
    bonded: "",
    RAC: "",
  },

  {
    name: "Amara",
    image: "css/rabbitAssets/rabbitImages/Amara.png",
    breed: "Mini Rex",
    sex: "Female",
    age: "1 Year, 1 Month",
    weight: "4.1 Pounds",
    bio: "Hi there! My name is Amara because I was rescued during the week of Valentine’s Day. I was found in a backyard on Grissom all on my own, living under a deck. When I was first rescued, I didn’t trust these giants too much and hid from them. But after about a day, I decided they weren’t going to hurt me and began to trust them a bit more. Now I love my indoor house bunny life! <br> <br> I like to explore everywhere, so bunny proofing needs to be a priority with me! I’m a mini-Rex so I’m super soft, and I absolutely love pets. I’ll even come to you and ask for them!",
    bonded: "",
    RAC: "",
  },

  {
    name: "Beatrice",
    image: "css/rabbitAssets/rabbitImages/Beatrice.png",
    breed: "Lionhead Mix",
    sex: "Female",
    age: "2 Years, 2 Months",
    weight: "4 Pounds",
    bio: "Hello I’m Beatrice! I was found with 55 other buns abandoned outside. While she prefers to approach you, than to be approached, she loves hopping on the couch and asking for pets. Beatrice is really good with her litterbox, and likes to keep her pen tidy. <br> <br> Beatrice loves toys, treats, and adventuring around the house. I am so lucky to be bonded with another female Dahlia that was rescued with me! While Dahlia and I live together, we prefer to have their own litter boxes for now.",
    bonded: "<p>I'm part of a bonded pair with <span>Dahlia</span>!</p>",
    RAC: "",
  },

  {
    name: "Blini",
    image: "css/rabbitAssets/rabbitImages/Blini.png",
    breed: "Mix",
    sex: "Female",
    age: "9 Months",
    weight: "5.6 Pounds",
    bio: "Hi, I'm Blini! I'm new here and looking for my forever family. I was born in a camp where my humans didn't have a home to live in so my mom and siblings and I were just roaming free outside. It was scary and I am very happy to be an indoor house bunny now. <br> <br> I am slightly shy with new people and places, but I'm curious and if you give me time, we might just be best friends. I have spent a lot of time with my brothers and sisters and might like a friend someday.",
    bonded: false,
    RAC: false,
  },

  {
    name: "Brooks",
    image: "css/rabbitAssets/rabbitImages/Brooks.png",
    breed: "Harlequin Mix",
    sex: "Male",
    age: "8 Months",
    weight: "7.7 Pounds",
    bio: "Hi, I'm Brooks! I was found running loose in a public park in the winter. Thankfully a nice person caught me and got me fixed up at the vet! I'm still fairly young and I am going to be a big boy. I'm very sweet and I like exploring. I like the resident cat too!",
    bonded: false,
    RAC: true,
  },

  {
    name: "Cagney",
    image: "css/rabbitAssets/rabbitImages/Cagney.png",
    breed: "New Zealand",
    sex: "Female",
    age: "1 Year, 3 Months",
    weight: "7.1 Pounds",
    bio: "Hi, I'm Cagney and I'm best friends with my sister Lacey! We are looking for a home together. We are pretty young and such beautiful girls. We are looking forward to chilling out at your place and having all the good food! Would you like to meet us and feel how soft we are?",
    bonded: true,
    RAC: false,
  },

  {
    name: "Chestnut",
    image: "css/rabbitAssets/rabbitImages/Chestnut.png",
    breed: "Mix",
    sex: "Female",
    age: "7 Months",
    weight: "3.9 Pounds",
    bio: "Hi, I'm Chestnut and I'm new here! Please stay tuned for more info on what kind of family I'd like. :)",
    bonded: false,
    RAC: false,
  },

  {
    name: "Coco",
    image: "css/rabbitAssets/rabbitImages/Coco.png",
    breed: "Mix",
    sex: "Female",
    age: "2 Years, 11 Months",
    weight: "5 Pounds",
    bio: "Coco and four other rabbits were found wondering around a neighborhood in Merrillville, IN. Since is grateful to be a house rabbit and settled in quickly. <br> <br>  Coco is a very curious, social with both people and other rabbits, and loves to be petted. Her play area is full of toys and Coco bunstructed a custom made playhouse from a cardboard box. She is a very busy girl! <br><br> Coco would do well in a home where she has alot of space to run around and explore as she is full of energy. <br> <br> Do you have space in your heart to give this cutie a forever home?",
    bonded: false,
    RAC: false,
  },

  {
    name: "Crepe",
    image: "css/rabbitAssets/rabbitImages/Crepe.png",
    breed: "Mix",
    sex: "Female",
    age: "11 Months",
    weight: "5.6 Pounds",
    bio: "Hi, I'm Crepe! I'm new here and looking for my forever family I was born in a camp where my humans didn't have a home to live in so my mom and siblings and I were just roaming free outside. It was scary and I am very happy to be an indoor house bunny now. I am slightly shy with new people and places, but I'm curious and if you give me time, we might just be best friends. I have spent a lot of time with my brothers and sisters and might like a bunny friend someday.",
    bonded: "",
    RAC: false,
  },

  {
    name: "Chestnut",
    image: "css/rabbitAssets/rabbitImages/Chestnut.png",
    breed: "Mix",
    sex: "Female",
    age: "7 Months",
    weight: "3.9 Pounds",
    bio: "Hi, I'm Chestnut and I'm new here! Please stay tuned for more info on what kind of family I'd like. :)",
    bonded: false,
    RAC: false,
  },

  {
    name: "Chestnut",
    image: "css/rabbitAssets/rabbitImages/Chestnut.png",
    breed: "Mix",
    sex: "Female",
    age: "7 Months",
    weight: "3.9 Pounds",
    bio: "Hi, I'm Chestnut and I'm new here! Please stay tuned for more info on what kind of family I'd like. :)",
    bonded: false,
    RAC: false,
  },

  {
    name: "Chestnut",
    image: "css/rabbitAssets/rabbitImages/Chestnut.png",
    breed: "Mix",
    sex: "Female",
    age: "7 Months",
    weight: "3.9 Pounds",
    bio: "Hi, I'm Chestnut and I'm new here! Please stay tuned for more info on what kind of family I'd like. :)",
    bonded: false,
    RAC: false,
  },

  {
    name: "Chestnut",
    image: "css/rabbitAssets/rabbitImages/Chestnut.png",
    breed: "Mix",
    sex: "Female",
    age: "7 Months",
    weight: "3.9 Pounds",
    bio: "Hi, I'm Chestnut and I'm new here! Please stay tuned for more info on what kind of family I'd like. :)",
    bonded: false,
    RAC: false,
  },

  {
    name: "Chestnut",
    image: "css/rabbitAssets/rabbitImages/Chestnut.png",
    breed: "Mix",
    sex: "Female",
    age: "7 Months",
    weight: "3.9 Pounds",
    bio: "Hi, I'm Chestnut and I'm new here! Please stay tuned for more info on what kind of family I'd like. :)",
    bonded: false,
    RAC: false,
  },

  {
    name: "Chestnut",
    image: "css/rabbitAssets/rabbitImages/Chestnut.png",
    breed: "Mix",
    sex: "Female",
    age: "7 Months",
    weight: "3.9 Pounds",
    bio: "Hi, I'm Chestnut and I'm new here! Please stay tuned for more info on what kind of family I'd like. :)",
    bonded: false,
    RAC: false,
  },

  {
    name: "Chestnut",
    image: "css/rabbitAssets/rabbitImages/Chestnut.png",
    breed: "Mix",
    sex: "Female",
    age: "7 Months",
    weight: "3.9 Pounds",
    bio: "Hi, I'm Chestnut and I'm new here! Please stay tuned for more info on what kind of family I'd like. :)",
    bonded: false,
    RAC: false,
  },

  {
    name: "Chestnut",
    image: "css/rabbitAssets/rabbitImages/Chestnut.png",
    breed: "Mix",
    sex: "Female",
    age: "7 Months",
    weight: "3.9 Pounds",
    bio: "Hi, I'm Chestnut and I'm new here! Please stay tuned for more info on what kind of family I'd like. :)",
    bonded: false,
    RAC: false,
  },

  {
    name: "Chestnut",
    image: "css/rabbitAssets/rabbitImages/Chestnut.png",
    breed: "Mix",
    sex: "Female",
    age: "7 Months",
    weight: "3.9 Pounds",
    bio: "Hi, I'm Chestnut and I'm new here! Please stay tuned for more info on what kind of family I'd like. :)",
    bonded: false,
    RAC: false,
  },

  {
    name: "Chestnut",
    image: "css/rabbitAssets/rabbitImages/Chestnut.png",
    breed: "Mix",
    sex: "Female",
    age: "7 Months",
    weight: "3.9 Pounds",
    bio: "Hi, I'm Chestnut and I'm new here! Please stay tuned for more info on what kind of family I'd like. :)",
    bonded: false,
    RAC: false,
  },

  {
    name: "Chestnut",
    image: "css/rabbitAssets/rabbitImages/Chestnut.png",
    breed: "Mix",
    sex: "Female",
    age: "7 Months",
    weight: "3.9 Pounds",
    bio: "Hi, I'm Chestnut and I'm new here! Please stay tuned for more info on what kind of family I'd like. :)",
    bonded: false,
    RAC: false,
  },

  {
    name: "Chestnut",
    image: "css/rabbitAssets/rabbitImages/Chestnut.png",
    breed: "Mix",
    sex: "Female",
    age: "7 Months",
    weight: "3.9 Pounds",
    bio: "Hi, I'm Chestnut and I'm new here! Please stay tuned for more info on what kind of family I'd like. :)",
    bonded: false,
    RAC: false,
  },

  {
    name: "Chestnut",
    image: "css/rabbitAssets/rabbitImages/Chestnut.png",
    breed: "Mix",
    sex: "Female",
    age: "7 Months",
    weight: "3.9 Pounds",
    bio: "Hi, I'm Chestnut and I'm new here! Please stay tuned for more info on what kind of family I'd like. :)",
    bonded: false,
    RAC: false,
  },

  {
    name: "Chestnut",
    image: "css/rabbitAssets/rabbitImages/Chestnut.png",
    breed: "Mix",
    sex: "Female",
    age: "7 Months",
    weight: "3.9 Pounds",
    bio: "Hi, I'm Chestnut and I'm new here! Please stay tuned for more info on what kind of family I'd like. :)",
    bonded: false,
    RAC: false,
  },

  {
    name: "Chestnut",
    image: "css/rabbitAssets/rabbitImages/Chestnut.png",
    breed: "Mix",
    sex: "Female",
    age: "7 Months",
    weight: "3.9 Pounds",
    bio: "Hi, I'm Chestnut and I'm new here! Please stay tuned for more info on what kind of family I'd like. :)",
    bonded: false,
    RAC: false,
  },

  {
    name: "Chestnut",
    image: "css/rabbitAssets/rabbitImages/Chestnut.png",
    breed: "Mix",
    sex: "Female",
    age: "7 Months",
    weight: "3.9 Pounds",
    bio: "Hi, I'm Chestnut and I'm new here! Please stay tuned for more info on what kind of family I'd like. :)",
    bonded: false,
    RAC: false,
  },

  {
    name: "Chestnut",
    image: "css/rabbitAssets/rabbitImages/Chestnut.png",
    breed: "Mix",
    sex: "Female",
    age: "7 Months",
    weight: "3.9 Pounds",
    bio: "Hi, I'm Chestnut and I'm new here! Please stay tuned for more info on what kind of family I'd like. :)",
    bonded: false,
    RAC: false,
  },

  {
    name: "Chestnut",
    image: "css/rabbitAssets/rabbitImages/Chestnut.png",
    breed: "Mix",
    sex: "Female",
    age: "7 Months",
    weight: "3.9 Pounds",
    bio: "Hi, I'm Chestnut and I'm new here! Please stay tuned for more info on what kind of family I'd like. :)",
    bonded: false,
    RAC: false,
  },

  {
    name: "Chestnut",
    image: "css/rabbitAssets/rabbitImages/Chestnut.png",
    breed: "Mix",
    sex: "Female",
    age: "7 Months",
    weight: "3.9 Pounds",
    bio: "Hi, I'm Chestnut and I'm new here! Please stay tuned for more info on what kind of family I'd like. :)",
    bonded: false,
    RAC: false,
  },

  {
    name: "Chestnut",
    image: "css/rabbitAssets/rabbitImages/Chestnut.png",
    breed: "Mix",
    sex: "Female",
    age: "7 Months",
    weight: "3.9 Pounds",
    bio: "Hi, I'm Chestnut and I'm new here! Please stay tuned for more info on what kind of family I'd like. :)",
    bonded: false,
    RAC: false,
  },

  {
    name: "Chestnut",
    image: "css/rabbitAssets/rabbitImages/Chestnut.png",
    breed: "Mix",
    sex: "Female",
    age: "7 Months",
    weight: "3.9 Pounds",
    bio: "Hi, I'm Chestnut and I'm new here! Please stay tuned for more info on what kind of family I'd like. :)",
    bonded: false,
    RAC: false,
  },

  {
    name: "Chestnut",
    image: "css/rabbitAssets/rabbitImages/Chestnut.png",
    breed: "Mix",
    sex: "Female",
    age: "7 Months",
    weight: "3.9 Pounds",
    bio: "Hi, I'm Chestnut and I'm new here! Please stay tuned for more info on what kind of family I'd like. :)",
    bonded: false,
    RAC: false,
  },

  {
    name: "Chestnut",
    image: "css/rabbitAssets/rabbitImages/Chestnut.png",
    breed: "Mix",
    sex: "Female",
    age: "7 Months",
    weight: "3.9 Pounds",
    bio: "Hi, I'm Chestnut and I'm new here! Please stay tuned for more info on what kind of family I'd like. :)",
    bonded: false,
    RAC: false,
  },

  {
    name: "Chestnut",
    image: "css/rabbitAssets/rabbitImages/Chestnut.png",
    breed: "Mix",
    sex: "Female",
    age: "7 Months",
    weight: "3.9 Pounds",
    bio: "Hi, I'm Chestnut and I'm new here! Please stay tuned for more info on what kind of family I'd like. :)",
    bonded: false,
    RAC: false,
  },

  {
    name: "Chestnut",
    image: "css/rabbitAssets/rabbitImages/Chestnut.png",
    breed: "Mix",
    sex: "Female",
    age: "7 Months",
    weight: "3.9 Pounds",
    bio: "Hi, I'm Chestnut and I'm new here! Please stay tuned for more info on what kind of family I'd like. :)",
    bonded: false,
    RAC: false,
  },

  {
    name: "Chestnut",
    image: "css/rabbitAssets/rabbitImages/Chestnut.png",
    breed: "Mix",
    sex: "Female",
    age: "7 Months",
    weight: "3.9 Pounds",
    bio: "Hi, I'm Chestnut and I'm new here! Please stay tuned for more info on what kind of family I'd like. :)",
    bonded: false,
    RAC: false,
  },

  {
    name: "Chestnut",
    image: "css/rabbitAssets/rabbitImages/Chestnut.png",
    breed: "Mix",
    sex: "Female",
    age: "7 Months",
    weight: "3.9 Pounds",
    bio: "Hi, I'm Chestnut and I'm new here! Please stay tuned for more info on what kind of family I'd like. :)",
    bonded: false,
    RAC: false,
  },

  {
    name: "Chestnut",
    image: "css/rabbitAssets/rabbitImages/Chestnut.png",
    breed: "Mix",
    sex: "Female",
    age: "7 Months",
    weight: "3.9 Pounds",
    bio: "Hi, I'm Chestnut and I'm new here! Please stay tuned for more info on what kind of family I'd like. :)",
    bonded: false,
    RAC: false,
  },
];
