export var RABBITS = [
  {
    name: "Akua",
    image: "css/rabbitAssets/rabbitImages/Akua.png",
    breed: "Drawf Mix",
    sex: "Female",
    age: "8 Months",
    weight: "4 Pounds",
    bio: "I'm Akua and I'm new here! I was found running loose for at least a month, it was cold out and hard to find food! I'm happy to be a house rabbit now. <br>  <br>I am a very sweet bunny and very curious. I love my run time! My foster family says I can be shy at first and may take a little more time warming up to a person. Once I warm up, I want attention and enjoy being petted!",
    bonded: "",
    RAC: "",
  },

  {
    name: "Amara",
    image: "css/rabbitAssets/rabbitImages/Amara.png",
    breed: "Mini Rex",
    sex: "Female",
    age: "1 Year, 1 Month",
    weight: "4.1 Pounds",
    bio: "Hi there! My name is Amara because I was rescued during the week of Valentine’s Day. I was found in a backyard on Grissom all on my own, living under a deck. When I was first rescued, I didn’t trust these giants too much and hid from them. But after about a day, I decided they weren’t going to hurt me and began to trust them a bit more. Now I love my indoor house bunny life! <br> <br> I like to explore everywhere, so bunny proofing needs to be a priority with me! I’m a mini-Rex so I’m super soft, and I absolutely love pets. I’ll even come to you and ask for them!",
    bonded: "",
    RAC: "",
  },

  {
    name: "Beatrice",
    image: "css/rabbitAssets/rabbitImages/Beatrice.png",
    breed: "Lionhead Mix",
    sex: "Female",
    age: "2 Years, 2 Months",
    weight: "4 Pounds",
    bio: "Hello I’m Beatrice! I was found with 55 other buns abandoned outside. While she prefers to approach you, than to be approached, she loves hopping on the couch and asking for pets. Beatrice is really good with her litterbox, and likes to keep her pen tidy. <br> <br> Beatrice loves toys, treats, and adventuring around the house. I am so lucky to be bonded with another female Dahlia that was rescued with me! While Dahlia and I live together, we prefer to have their own litter boxes for now.",
    bonded: "I'm part of a bonded pair with Dahlia!",
    RAC: "",
  },

  {
    name: "Blini",
    image: "css/rabbitAssets/rabbitImages/Blini.png",
    breed: "Mix",
    sex: "Female",
    age: "9 Months",
    weight: "5.6 Pounds",
    bio: "Hi, I'm Blini! I'm new here and looking for my forever family. I was born in a camp where my humans didn't have a home to live in so my mom and siblings and I were just roaming free outside. It was scary and I am very happy to be an indoor house bunny now. <br> <br> I am slightly shy with new people and places, but I'm curious and if you give me time, we might just be best friends. I have spent a lot of time with my brothers and sisters and might like a friend someday.",
    bonded: "",
    RAC: "",
  },

  {
    name: "Brooks",
    image: "css/rabbitAssets/rabbitImages/Brooks.png",
    breed: "Harlequin Mix",
    sex: "Male",
    age: "8 Months",
    weight: "7.7 Pounds",
    bio: "Hi, I'm Brooks! I was found running loose in a public park in the winter. Thankfully a nice person caught me and got me fixed up at the vet! I'm still fairly young and I am going to be a big boy. I'm very sweet and I like exploring. I like the resident cat too!",
    bonded: "",
    RAC: "I am at the Rabbit Adoption Center! Come visit me!",
  },

  {
    name: "Cagney",
    image: "css/rabbitAssets/rabbitImages/Cagney.png",
    breed: "New Zealand",
    sex: "Female",
    age: "1 Year, 3 Months",
    weight: "7.1 Pounds",
    bio: "Hi, I'm Cagney and I'm best friends with my sister Lacey! We are looking for a home together. We are pretty young and such beautiful girls. We are looking forward to chilling out at your place and having all the good food! Would you like to meet us and feel how soft we are?",
    bonded: "I'm part of a bonded pair with Lacey!",
    RAC: "",
  },

  {
    name: "Chestnut",
    image: "css/rabbitAssets/rabbitImages/Chestnut.png",
    breed: "Mix",
    sex: "Female",
    age: "7 Months",
    weight: "3.9 Pounds",
    bio: "Hi, I'm Chestnut and I'm new here! So far, I am getting along very well with the humans taking care of me, now that I've gotten to know them. <br> <br>Please stay tuned for more info on what kind of family I'd like :)",
    bonded: "",
    RAC: "",
  },

  {
    name: "Coco",
    image: "css/rabbitAssets/rabbitImages/Coco.png",
    breed: "Mix",
    sex: "Female",
    age: "2 Years, 11 Months",
    weight: "5 Pounds",
    bio: "Coco and four other rabbits were found wondering around a neighborhood in Merrillville, IN. Since is grateful to be a house rabbit and settled in quickly. <br> <br>  Coco is a very curious, social with both people and other rabbits, and loves to be petted. Her play area is full of toys and Coco bunstructed a custom made playhouse from a cardboard box. She is a very busy girl! <br><br> Coco would do well in a home where she has alot of space to run around and explore as she is full of energy. <br> <br> Do you have space in your heart to give this cutie a forever home?",
    bonded: "",
    RAC: "",
  },

  {
    name: "Crepe",
    image: "css/rabbitAssets/rabbitImages/Crepe.png",
    breed: "Mix",
    sex: "Female",
    age: "11 Months",
    weight: "5.6 Pounds",
    bio: "Hi, I'm Crepe! I'm new here and looking for my forever family I was born in a camp where my humans didn't have a home to live in so my mom and siblings and I were just roaming free outside. It was scary and I am very happy to be an indoor house bunny now. I am slightly shy with new people and places, but I'm curious and if you give me time, we might just be best friends. I have spent a lot of time with my brothers and sisters and might like a bunny friend someday.",
    bonded: "",
    RAC: "",
  },

  {
    name: "Dhalia",
    image: "css/rabbitAssets/rabbitImages/Dhalia.png",
    breed: "Lionhead Mix",
    sex: "Female",
    age: "2 Years, 4 Months",
    weight: "6 Pounds",
    bio: "Hello I’m Dahlia! I was one of many bunnies that were abandoned outside. I’m a bit timid but I enjoy laying on my foster and getting pets. I am still working on trusting humans, but I have really come out of my shell now that I’m bonded with my friend Beatrice. I really like finding a quiet spot, and watching Beatrice while she plays. While Beatrice and I live together, we prefer to have their own litter boxes for now.",
    bonded: "I'm part of a bonded pair with Beatrice!",
    RAC: "",
  },

  {
    name: "Gizmo",
    image: "css/rabbitAssets/rabbitImages/Gizmo.png",
    breed: "Lionhead Mix",
    sex: "Female",
    age: "2 Years, 7 Months",
    weight: "6.1 Pounds",
    bio: "Hi, my name is Gizmo and I was born on a playground! I'm glad I made it to rescue right away to grow up safe. My foster mama said I have really long legs and I do really good dead bunny flop. I am full of energy and love to do binkies and bunny 500. I am also a proud paper shredder and love to tear apart phone books and trash mail.  I prefer not to be picked up but love to hang out on your belly as long as you pet my head the way I like. <br> <br> I was recently returned to rescue and I'm getting used to things again! I will need a family that is pretty bunny savvy because I am quite territorial over my space and my enclosure. You will need to speak fluent bunny so you can understand my boundaries and how to approach me. I probably would do best in a home with only adults - it can be hard for young ones to understand my language and not approach me when I need alone time. If you are an experienced bunny savvy person who's up for the challenge of learning how I like things, then maybe we can be best friends! ",
    bonded: "",
    RAC: "",
  },

  {
    name: "Gizzy",
    image: "css/rabbitAssets/rabbitImages/Gizzy.png",
    breed: "Lionhead",
    sex: "Female",
    age: "8 Months",
    weight: "2.7 Pounds",
    bio: "I'm a teeny little fluff ball named Gizzy. Someone left me in a cage next to a dumpster! Fortunately someone found me and took care of me. I am a very shy and skittish bunny, so I'll need a quiet family who can give me space and patience. I will need some grooming for my luxurious wool.",
    bonded: "",
    RAC: "",
  },

  {
    name: "Isabunna",
    image: "css/rabbitAssets/rabbitImages/Isabunna.png",
    breed: "Mini Lop",
    sex: "Female",
    age: "1 Year, 9 Months",
    weight: "5.9 Pounds",
    bio: "Hi, I'm Isabunna, or Izzy! I was found running loose in a Vincennes neighborhood. I'm happy to be inside now with nice people! I'm quiet and have rich, soft fur. I like to lounge like a diva! But you must know.... I do have some attitude! I am not fond of new things or people, and sometimes I am a little grumpy about that. But if you are patient with me and let me do my thing, eventually I will allow (and maybe enjoy but never admit!) head pets. I would love to find a forever home with patient folks that have a slightly more quiet pace of life and know how to speak bunny. I love to chew toys and fling baby keys around. My foster mom says I have to have a topper on my pen now because I learned how to jump out.",
    bonded: "",
    RAC: "",
  },

  {
    name: "Isla",
    image: "css/rabbitAssets/rabbitImages/Isla.png",
    breed: "Mix",
    sex: "Female",
    age: "3 Years",
    weight: "3.6 Pounds",
    bio: "Hi I’m Isla! I was a shy girl when I was found outside but I’ve learned to love being a spoiled house bun. I’m a tiny gal and probably not the best match for young children. I am extremely interactive with my people and LOVE to cuddle. You can pet me as long as you want. If you stop petting me maybe I’ll give you a little nip to let you know you’re not done. I can be spunky like that. I would love to meet you and find my forever family!",
    bonded: "",
    RAC: "",
  },

  {
    name: "Jo",
    image: "css/rabbitAssets/rabbitImages/Jo.png",
    breed: "New Zealand Mix",
    sex: "Female",
    age: "1 Year",
    weight: "6 Pounds",
    bio: "Hi, I'm Jo and I'm friends with my sister Meg! We need to be adopted together. We are super cute! We are very friendly and curious and confidant. We love to lounge around together and keep our foster mom laughing with our napping positions. We would love to meet you and maybe be best friends!",
    bonded: "I'm part of a bonded pair with Meg!",
    RAC: "",
  },

  {
    name: "Lacey",
    image: "css/rabbitAssets/rabbitImages/Lacey.png",
    breed: "New Zealand",
    sex: "Female",
    age: "1 Year, 3 Months",
    weight: "8.2 Pounds",
    bio: "Hi, I'm Lacey and I'm best friends with my sister Cagney! We are looking for a home together. We are pretty young and such beautiful girls. We are looking forward to chilling out at your place and having all the good food! Would you like to meet us and feel how soft we are?",
    bonded: "I'm part of a bonded pair with Cagney!",
    RAC: "",
  },

  {
    name: "Lani",
    image: "css/rabbitAssets/rabbitImages/Lani.png",
    breed: "Dwarf Mix",
    sex: "Female",
    age: "10 Months",
    weight: "4.4 Pounds",
    bio: "I'm Lani and I'm new here! I was found running loose for at least a month, it was cold out and hard to find food! I'm happy to be a house rabbit now and I'm already good with my litterbox and excited for people to bring me food. :)",
    bonded: "",
    RAC: "I'm at the Ra bbit Adoption Center! Come visit me!",
  },

  {
    name: "Lofte",
    image: "css/rabbitAssets/rabbitImages/Lofte.png",
    breed: "English Spot",
    sex: "Female",
    age: "4 Years, 6 Months",
    weight: "10.5 Pounds",
    bio: "Hi, my name is Lofte! I was abandoned in a filthy cage on the side of the road, I was starving and had lost all of the fur on my underside. My foster family is the BEST!! My foster mom says that I am a Cookie Monster :) My fur has completely grown back and i have gained weight. <br><br>I am super curious about what you are doing in my space. I do not like it when you move my toys around and will be literally on top of you when you are in my space!! I love to dig and chew, so foster mom says I will need lots of enrichment and supervision. <br><br> I will need an adopter who will spend a TON of time with me, work to help me feel secure, continue to help me gain weight, and respect my space.",
    bonded: "",
    RAC: "",
  },

  {
    name: "Lucky",
    image: "css/rabbitAssets/rabbitImages/Lucky.png",
    breed: "New Zealand Mix",
    sex: "Male",
    age: "1 Year, 1 Month",
    weight: "5.9 Pounds",
    bio: "Hi, I'm Lucky! I'm a new arrival to rescue after having been found running on a busy road. I'm feeling better after seeing the vet and now I'm looking for my forever home!",
    bonded: "",
    RAC: "",
  },

  {
    name: "Maxine",
    image: "css/rabbitAssets/rabbitImages/Maxine.png",
    breed: "Dutch",
    sex: "Female",
    age: "8 Months",
    weight: "3.7 Pounds",
    bio: "Hi, I'm Maxine, and someone dumped me outside in the cold along a recreational trail in Indy! Thankfully nice people worked for several days to capture me. I was covered in hundreds of ticks! I was so happy to get inside with good food and nice folks. Now I'm all fixed up and I am a super fun bunny! I love attention, playing, and escaping to explore the whole house. I get along pretty well with the other foster buns here too. Who wants to meet me and take me home?!",
    bonded: "",
    RAC: "I'm at the Rabbit Adoption Center! Come visit me!",
  },

  {
    name: "Meg",
    image: "css/rabbitAssets/rabbitImages/Meg.png",
    breed: "Mix",
    sex: "Female",
    age: "7 Months",
    weight: "3.9 Pounds",
    bio: "Hi, I'm Meg and I'm friends with my sister Jo! We need to be adopted together. We are super cute! We are super cute! We are very friendly and curious and confidant. We love to lounge around together and keep our foster mom laughing with our napping positions. We would love to meet you and maybe be best friends!",
    bonded: "I'm part of a bonded pair with Jo!",
    RAC: "",
  },

  {
    name: "Meringue",
    image: "css/rabbitAssets/rabbitImages/Meringue.png",
    breed: "Dutch Mix",
    sex: "Female",
    age: "11 Months",
    weight: "5.1 Pounds",
    bio: "Hi, I'm Meringue and I'm new here! I'm looking for my forever family. I was born in a camp where my humans didn't have a home to live in so my mom and siblings and I were just roaming free outside. It was scary and I am very happy to be an indoor house bunny now. I am slightly shy with new people and places, but I'm curious and if you give me time, we might just be best friends. I have spent a lot of time with my brothers and sisters and might like a bunny friend someday.",
    bonded: "",
    RAC: "",
  },

  {
    name: "Nash",
    image: "css/rabbitAssets/rabbitImages/Nash.png",
    breed: "Dutch",
    sex: "Male",
    age: "3 Years, 10 Months",
    weight: "4.2 Pounds",
    bio: "Hi I’m Nash, I came to IHRS with some dental issues and I was a VERY grumpy guy. My foster mom called me Nash Smash because I was cranky like the Hulk. My teeth are all fixed up now and I’ve much happier…. Still a little moody so I do need someone that speaks bunny and will be patient with me and take me to the vet regularly to make sure my teeth stay healthy. I’m a little high maintenance but I’m super cute so I get away with it. I love to run and explore and play in my tunnel. I’m a big foodie and get super excited during dinner time. I’ll grab my toys and run around in circles with them! I especially love my teddy bear. I’m great with my litter box and keep my space tidy. When I know I can trust you, I’ll hop all over you. I like head pets but I don’t like you anywhere near my tail. Stay out of my danger zone and we can stay friends. I’m a good free roam candidate, and a really good helper. I follow you around incase you drop any treats and I’ll clean them right up! I’m excited to find my forever family so come meet me!",
    bonded: "",
    RAC: "",
  },

  {
    name: "Parker",
    image: "css/rabbitAssets/rabbitImages/Parker.png",
    breed: "English Spot Mix",
    sex: "Male",
    age: "8 Months",
    weight: "7.7 Pounds",
    bio: "Hi, I'm Parker! I was found running loose in a public park in the winter. Thankfully a nice person caught me and got me fixed up at the vet! I'm still fairly young and I am going to be a big boy. I'm very sweet and I like exploring.",
    bonded: "",
    RAC: "I'm at the Rabbit Adoption Center! Come visit me!",
  },

  {
    name: "Parsnip",
    image: "css/rabbitAssets/rabbitImages/Parsnip.png",
    breed: "Mix",
    sex: "Female",
    age: "7 Months",
    weight: "3.9 Pounds",
    bio: "Hi, I'm Parsnip and I'm new here! So far, I am getting along very well with the humans taking care of me, now that I've gotten to know them. <br> <br>Please stay tuned for more info on what kind of family I'd like :)",
    bonded: "",
    RAC: "",
  },

  {
    name: "Petey",
    image: "css/rabbitAssets/rabbitImages/Petey.png",
    breed: "New Zealand Mix",
    sex: "Male",
    age: "11 Months",
    weight: "8 Pounds",
    bio: "Hi, I'm Petey! I'm bonded to my brother Razzle and we need to be adopted together. I'm still growing emotionally, but pretty well full grown size wise! <br> <br> We love being together and sometimes launch WWIII in our pen as we chase each other and then freeze! We love to be petted, my brother somewhat more than I do. When given run time, we are both brave explorers who will occasionally surprise each other resulting in jumps and runs! <br> <br> We are still learning our litterbox :)",
    bonded: "I'm part of a bonded pair with Razzle!",
    RAC: "",
  },

  {
    name: "Pinto",
    image: "css/rabbitAssets/rabbitImages/Pinto.png",
    breed: "Mix",
    sex: "Male",
    age: "7 Months",
    weight: "7.3 Pounds",
    bio: "Hi I’m Pinto! I was found outside on a super rainy day. I was so tired of being stuck outside & ready to be a house rabbit that I just let one of the rescuers walk up to me & pick me up. I know no stranger but my favorite people are the ones with a treat for me. I like to run and binky and play in the long curtains. I am a good free roam candidate. I’m still young and have a lot of energy so I will need lots of play time. I would love to meet you!",
    bonded: "",
    RAC: "I'm at the Rabbit Adoption Center! Come visit me!",
  },

  {
    name: "Razzle",
    image: "css/rabbitAssets/rabbitImages/Razzle.png",
    breed: "New Zealand Mix",
    sex: "Male",
    age: "11 Months",
    weight: "8.5 Pounds",
    bio: "Hi, I'm Razzle! I'm bonded to my brother Petey and we need to be adopted together. I'm still growing emotionally, but pretty well full grown size wise! <br> <br> We love being together and sometimes launch WWIII in our pen as we chase each other and then freeze! We love to be petted, me somewhat more than my brother. When given run time, we are both brave explorers who will occasionally surprise each other resulting in jumps and runs! <br <br> We are still learning our litterbox :)",
    bonded: "I'm part of a bonded pair with Petey!",
    RAC: "",
  },

  {
    name: "Rebel",
    image: "css/rabbitAssets/rabbitImages/Rebel.png",
    breed: "Lionhead",
    sex: "Female",
    age: "1 Year, 10 Months",
    weight: "4.1 Pounds",
    bio: "Hi, I'm Rebel! I found myself at the city shelter and then came to rescue when I wasn't feeling so good. They got me fixed up and now I'm excited to start the next part of my life with a new family! I'm curious and playful, though I can be just a bit shy when I first meet you. I'm getting better with my litterbox too! I'm a little teeny girl and am super duper adorable! <br> <br> I have a secret: I need a special adopter. Whenever I have a big change in my life, like going from the shelter to a foster home, or then moving to a new foster home, or going to the vet .... I stop eating and pooping! I mean I take my hunger strikes VERY seriously. That's pretty bad news for a bunny. I'm looking for a family who can help me through this by minimizing change and stress in my life, and will keep my world pretty calm and consistent. I also need someone who knows how to treat a bunny who isn't feeling well in case I decide to go on one of my famous hunger strikes. When that happens, usually I need someone to help me out with special hand feeding, fluids, and carefully watching me. Do you have the special touch to be my person?",
    bonded: "",
    RAC: "",
  },

  {
    name: "Rosevie",
    image: "css/rabbitAssets/rabbitImages/rosevie2.png",
    breed: "Mix",
    sex: "Female",
    age: "2 Years, 2 Months",
    weight: "5 Pounds",
    bio: "Hi I'm Rosevie! I was found outside as a baby and I really like being a house rabbit. I have great litter box habits and love my free roam time. I am a little shy at first but can be persuaded with treats. I prefer to interact with you when you are on my level. My foster family has spent a lot of time helping me to trust & be a confident girl. They will make fun obstacle courses for me to run through, jump on, & hide under. I love it because I am adventurous and love to explore. I find foraging for food super fun. I love to zoom around as fast as I can and I will binky myself silly. After I have wore myself out I like laying around relaxing. I’m a fun girl with a big personality & I can’t wait to meet you!",
    bonded: "",
    RAC: "",
  },

  {
    name: "Scone",
    image: "css/rabbitAssets/rabbitImages/Scone.png",
    breed: "Mix",
    sex: "Female",
    age: "11 Months",
    weight: "5 Pounds",
    bio: "Hi, I'm Scone! I'm new here and looking for my forever family. I was born in a camp where my humans didn't have a home to live in so my mom and siblings and I were just roaming free outside. It was scary and I am very happy to be an indoor house bunny now. I am slightly shy with new people and places, but I'm curious and if you give me time, we might just be best friends. I have spent a lot of time with my brothers and sisters and might like a bunny friend someday.",
    bonded: "",
    RAC: "",
  },

  {
    name: "Sigourney",
    image: "css/rabbitAssets/rabbitImages/Sigourney.png",
    breed: "Lionhead Mix",
    sex: "Female",
    age: "1 Year, 3 Months",
    weight: "5.4 Pounds",
    bio: "Hi I’m Sigourney, I was found outside running around in the cold but some nice people brought me inside and I’ve been loving house rabbit life! I like to throw toys in the air and zoom around. I’m very tidy when I’m out playing & I’m getting better with my litterbox everyday. I take a few days to warm up but after that you can give me some pets. My foster mom says I look like a cute little stuffed animal. I would love to meet you!",
    bonded: "",
    RAC: "I'm at the Rabbit Adoption Center! Come visit me!",
  },

  {
    name: "Sparrow",
    image: "css/rabbitAssets/rabbitImages/Sparrow.png",
    breed: "New Zealand Mix",
    sex: "Male",
    age: "1 Year",
    weight: "5.6 Pounds",
    bio: "Hi, I'm Sparrow! I am living with my brother right now, Wonka, and we'd love to be adopted together! We are very busy and playful because we are still very young. We love when our foster mom comes in, we all periscope to see what she brings! We eat a LOT of food because we are still growing. We are both very friendly and curious about everything going on around us. We get along with our furry foster siblings (dogs and cats) as well as all the humans we've met of all ages and sizes. We would probably be a good fit for even first time bunny family. <br> <br> Our dad and mom are both big bunnies, so we will be too! We are similar looking but have just enough difference that you can tell us apart. :)",
    bonded: "I'm part of a bonded pair with Wonka!",
    RAC: "",
  },

  {
    name: "Tanvi",
    image: "css/rabbitAssets/rabbitImages/Tanvi.png",
    breed: "Dwarf Mix",
    sex: "Female",
    age: "10 Months",
    weight: "3.3 Pounds",
    bio: "Hi, I'm the sweetest little girl named Tanvi! I was captured as a stray outdoors, and I love being inside with a family now. I'm very petite and tidy. I can't wait to meet my new family!",
    bonded: "",
    RAC: "",
  },

  {
    name: "Vanna",
    image: "css/rabbitAssets/rabbitImages/Vanna.png",
    breed: "Lionhead Mix",
    sex: "Female",
    age: "2 Years, 7 Months",
    weight: "5.1 Pounds",
    bio: "Hi I’m Vanna! I got a very glamorous name because of my fancy hairdo. I'm pretty sassy and I can get in trouble when I'm bored! But give me lots of playtime and I am much happier.<br> <br> I get really excited when people come by my pen. I really want attention and treats! Sometimes I lunge at hands in my pen, I'd rather come visit you outside the pen and not have hands over my head. It took a while until I would trust my people but now I let them groom my fur. My long pieces of fur tangle easily, so I will need a little grooming help. <br> <br> I have a big personality and I'm looking for a family who will let me show off! I'm probably best for older kids, not little ones.",
    bonded: "",
    RAC: "",
  },

  {
    name: "W'Kabi",
    image: "css/rabbitAssets/rabbitImages/Wkabi.png",
    breed: "New Zealand Mix",
    sex: "Male",
    age: "2 Years, 1 Month",
    weight: "11.4 Pounds",
    bio: "Hi! I’m W’Kabi, pronounced just as it looks! I was born to Ramonda in foster care. We’re all named after characters from the movie Black Panther. This all started because they said my mom looks like a Queen rabbit. <br> <br> I like to explore and get on the furniture. I also love cuddles and pets! I'm a very big boy so I'd rather climb on you or sit next to you than be picked up. I did well with kids. I prefer to have a lot of exploration space to live, instead of being cooped up. I might be grumpy if you reach over my head in a pen, but when I'm out and about I'd love to hang out! <br> <br> Do you need a very big bunny with one flopped ear in your life??",
    bonded: "",
    RAC: "",
  },

  {
    name: "Waldo",
    image: "css/rabbitAssets/rabbitImages/Waldo.png",
    breed: "New Zealand Mix",
    sex: "Male",
    age: "11 Months",
    weight: "7 Pounds",
    bio: "Hi, I'm Waldo! I'm a high energy, fun loving, running binkying bunny! I'm still growing emotionally, but pretty well full grown size wise. I might like to have a girlfriend! When I first meet you I might be a little shy. <br> <br> I love pets – until it's run time! Run time is fun time! I go from mild mannered bunny into wildebun! I like to tunnel and dig, jump and generally have a good buntime! <br> <br> I'm still learning my litterbox :)",
    bonded: "",
    RAC: "",
  },

  {
    name: "Wonka",
    image: "css/rabbitAssets/rabbitImages/Wonka.png",
    breed: "New Zealand Mix",
    sex: "Male",
    age: "1 Year",
    weight: "5.2 Pounds",
    bio: "Hi, I'm Wonka! I am living with my brother right now, Sparrow, and we'd love to be adopted together! We are very busy and playful because we are still very young. We love when our foster mom comes in, we all periscope to see what she brings! We eat a LOT of food because we are still growing. We are both very friendly and curious about everything going on around us. We get along with our furry foster siblings (dogs and cats) as well as all the humans we've met of all ages and sizes. We would probably be a good fit for even first time bunny family. <br> <br> Our dad and mom are both big bunnies, so we will be too! We are similar looking but have just enough difference that you can tell us apart. :)",
    bonded: "I'm part of a bonded pair with Sparrow!",
    RAC: "",
  },

  {
    name: "Xoliswa",
    image: "css/rabbitAssets/rabbitImages/Xoliswa.png",
    breed: "New Zealand",
    sex: "Female",
    age: "2 Years, 1 Month",
    weight: "9.1 Pounds",
    bio: "Hi, I’m Xoliswa! I love being petted!! I run up to the front of my enclosure when my foster family is in my room and follow them around soliciting attention. I also love playing with toys, especially those that I can pick up and toss and fling :). I have a really sweet personality and enjoy being around people. I get along with older people, dogs, and other rabbits, I might want a bunny friend some day. I would rather not be left alone for long periods of time, I love being around people so much! <br> <br> I need an adopter or a family who will spend a lot of time with me. I have lots of attitude and am a pretty forward bunny; since I am pretty sassy and forward (and I'm also a big girl!), I don't do very well with children, I will probably do best in a home with adults who know how to speak bunny. An experienced bunny person would be my dream mom or dad!",
    bonded: "",
    RAC: "",
  },
];

export var SANCTUARY = [
  {
    name: "Armand",
    image: "css/rabbitAssets/sanctuaryImages/Armand.png",
    breed: "Californian Mix",
    sex: "Male",
    age: "7 Years, 1 Month",
    weight: "6.6 Pounds",
    bio: "My name is Armand. I came to Indiana after escaping floods in Louisiana! <br> <br> I'm a very easygoing bunny and I enjoy house rabbit life! I love, love, love to be petted. You can pet me all day. I'm also a big fan of my daily salad and chowing on lots of hay! <br> <br> During play time I like to do binkies, and during rest time I stretch out and enjoy some sun coming in the window. <br> <br> The doctors have been unable to find the source of my GI troubles, I have had a LOT of tests! My foster mom does not mind the extra work and mess ;)",
  },

  {
    name: "Bellini",
    image: "css/rabbitAssets/sanctuaryImages/Bellini.png",
    breed: "Mix",
    sex: "Female",
    age: "4 Years, 2 Months",
    weight: "9.3 Pounds",
    bio: "I was rescued from a backyard hoarding situation in the winter, right after we had almost a foot of snow and negative windchill for almost a week. I had parasites along with several of the other rabbits I was living with, and on top of being sick, I was pregnant! Fortunately I came to rescue and was safe, warm, and well fed when I gave birth to my nine babies, and they have grown up healthy and loved. And my rescue family gave me the name Bellini! <br> <br> With everything I've been through, I'm still a sweet, mild tempered, patient, laid back bun. Unfortunately I started having problems breathing and began to get weak, I just couldn't get comfortable and was losing energy to even groom myself or my babies. I went to a special vet and they discovered I have an enlarged heart and I'm in congestive heart failure! <br> <br> Fortunately my babies were just old enough to go on their own a bit early, which allows me to take the medicine I need to feel better. Now that I have heart medicine, I've done a total turn around! I'm learning how to bunny for the first time. I can now do normal bunny things like groom myself, play with toys, binky, and even do zoomies! Due to my illness I'm not able to be spayed. The nice rescue people will let me live out the rest of my life being well taken care of in a healthy clean stable environment with the best care possible. My medical needs will last the rest of my life, and I could use donations to cover the costs of medicine and follow up diagnostics.",
  },

  {
    name: "Calamity Jane",
    image: "css/rabbitAssets/sanctuaryImages/calamityJane.png",
    breed: "Lionhead Mix",
    sex: "Female",
    age: "3 Years, 8 Months",
    weight: "3.8 Pounds",
    bio: "I'm Calamity Jane and I have a little attitude! I was pulled from a shelter and the vet discovered I had a couple of teeth that need some attention, they were sticking out through the bottom of my jaw! The nice rescue people got me set up with a bunny dentist so I can eat better. But then I just had more problems! My bad teeth were removed, and then I had a large abdominal mass removed, and THEN I had a kidney removed that was causing me a lot of problems! Wow! <br><br> I am a sassy girl but feeling much better now. I will need more dental surgeries, so I have a special foster home where they both appreciate my snark and can also provide me ongoing veterinary checkups. Hopefully my worst medical woes are behind me, but I will need continued monitoring of my teeth and my bloodwork to make sure my remaining kidney keeps up! It's working well now.",
  },

  {
    name: "Carlotta",
    image: "css/rabbitAssets/sanctuaryImages/Carlotta.png",
    breed: "Dutch",
    sex: "Female",
    age: "8 Years, 11 Months",
    weight: "3.9 Pounds",
    bio: "Hi, my name is Carlotta! I have severe acquired dental disease which requires periodic tooth trims and extractions. I have no molars on the right side of my mouth. I also have a lung abscess and limited lung space for air. You can see in the pic the black space is the only place I have to breathe. <br><br> Despite my medical conditions I am a super sweet and friendly girl :) I LOVE my pellets, I am super food motivated. I also love to binky! It's my second favorite thing! So I need regular run around time with new things to sniff, chin, and explore. I’m a huge cuddle and love to snuggle!",
  },

  {
    name: "Curly",
    image: "css/rabbitAssets/sanctuaryImages/Curly.png",
    breed: "Mix",
    sex: "Female",
    age: "6 Years, 2 Months",
    weight: "4.7 Pounds",
    bio: "Curly was found as a stray in Greenwood, very skinny and with eye infection. She was turned into an Indiana shelter, who helped get her weight back up and treated her eyes. But Curly was kind of stuck at the shelter... they didn't have a spay/neuter connection, and Curly was getting cranky about being there. IHRS came in to take Curly to rescue after care after she'd been at the shelter a couple of months. One thing we discovered while at the shelter: Curly had terribly maloccluded incisors! <br> <br> Curly had to learn to eat different kinds of food post her dental surgeries. She has trouble with grooming because she does not have teeth to help with that task. Her foster home helps her with this and Curly is good with cleaning as best she can with her tongue! The extent of her issues is so severe, her veterinarian feels she should remain in sanctuary status. She has an unknown prognosis overall and needs a very special caregiver with access to a great rabbit vet. We are supporting Curly with special foods and when she has recurrent dental/facial/eye infections she receives antibiotics and surgical correction. <br> <br> Curly is an incredibly happy bunny, especially because she is bonded to her best friend Violet, another special needs bunny! Violet and Curly snuggle a lot. We do have to separate them at mealtimes since Curly is very slow to chew her soft pellets and Violet tries to steal them all, but otherwise they spend all their time together. We are so happy they have found each other for comfort and friendship even though they both have serious health needs.",
  },

  {
    name: "Fitz",
    image: "css/rabbitAssets/sanctuaryImages/Fitz.png",
    breed: "Lionhead",
    sex: "Male",
    age: "2 Years, 3 Months",
    weight: "4 Pounds",
    bio: "Hi, I'm Fitz! I was born in rescue and my parents and siblings have all been adopted. But I get to stay with the rescue people because I'm a little differently abled! I'm a very special bunny who has a couple legs that don't work right and I get pretty dizzy and fall over a lot. I even had to have one of my eyes removed because I lay on my side so much it kept getting infected and very painful. But I'm all healed from that, and super happy with my bumpers to lean on, lots of great food, and my salads almost always have my favorite: fennel! <br> <br>I'm just hanging out doing my Fitzy thing. My foster people have to do a lot of care for me since I can't hop or use the litterbox, but I keep myself quite clean and I'm in charge of my day! My medical expenses have been more than most bunnies and I need food, hay, greens for the rest of my life, so donations to the rescue are always appreciated to help with my care.",
  },

  {
    name: "Kerplunk",
    image: "css/rabbitAssets/sanctuaryImages/Kerplunk.png",
    breed: "Lop Mix",
    sex: "Female",
    age: "8 Years, 7 Months",
    weight: "6.5 Pounds",
    bio: "Hi, my name is Kerplunk! I'm bonded to Kirby and we are a delightful pair with a lot of attitude. I'm the more shy between us, but that doesn't mean I'm afraid... I just like to do my own thing sometimes. If you have patience with me, you will be greatly rewarded by my big personality. My foster family loves watching Kirby and me; we make them laugh when we steal lettuce from each other! But we like to snuggle with each other as well. Kirby likes being pet a bit more than I do... but I do like to come up and see what my humans are up to! <br> <br> Kirby and I are fairly tidy outside of our litter box area, but we can make a mess there now and then. We like a big box! And I do tend to shed my fur quite a bit, so some grooming will definitely be required.",
  },

  {
    name: "Kirby",
    image: "css/rabbitAssets/sanctuaryImages/Kirby.png",
    breed: "Lop Mix",
    sex: "Male",
    age: "6 Years, 1 Month",
    weight: "6.4 Pounds",
    bio: "Hi, my name is Kirby and I'm a delightful bunny with a big attitude! I am bonded to Kerplunk and I'm the more outgoing of the pair. Sometimes I like to steal greens from Kerplunk, but don't worry, she can hold her own and steal them back! Our foster family loves watching us interact with each other, and laughing at our antics! Kerplunk isn't as interested in being petted, but I like pets for a limited amount of time. I can also do some champion flops if you watch me long enough. Work hard, play hard! <br> <br> I can make myself fairly tall when I periscope so some bunny proofing will be needed. If there is a way to escape my area, I will find it! Kerplunk and I are fairly tidy though, outside of our litter box area. We like to kick the hay out sometimes and just eat it next to the box... we definitely like an extra large box!",
  },

  {
    name: "Maybelline",
    image: "css/rabbitAssets/sanctuaryImages/Maybelline.png",
    breed: "Mix",
    sex: "Female",
    age: "5 Years, 1 Month",
    weight: "4.6 Pounds",
    bio: "I am Maybelline. I love having space to kick up my heels in my foster home. Being confined makes me very anxious. I have a fear that no one will respect my space like my foster mom does. <br> <br> I prefer to not be in a home with children, they make me nervous. I need a forever home with someone with prior rabbit experience, especially with rabbits who are slow to trust.",
  },

  {
    name: "Ramonda",
    image: "css/rabbitAssets/sanctuaryImages/Ramonda.png",
    breed: "New Zealand",
    sex: "Female",
    age: "4 Years, 2 Months",
    weight: "10.8 Pounds",
    bio: "This is Ramonda, named after the queen of Wakanda in the Black Panther movie, because she’s so stately and an old soul bunny. She’s very calm and very wise. How many bunnies could come from living in a less than ideal outdoor situation and have excellent litter box habits and take great care of 11 babies? She truly is a queen bunny. She loves treats and is an expert requester of treats (queens never beg). She likes head pets and attention but is also a pretty chill bunny. Her foster mom forgets to close and latch the pen and she’s quite content to stay put. As her babies are weaned and she gets her independence back, we’ll discover more about her personality.",
  },

  {
    name: "Ruby",
    image: "css/rabbitAssets/sanctuaryImages/Ruby.png",
    breed: "Standard Rex",
    sex: "Female",
    age: "8 Years, 6 Months",
    weight: "8 Pounds",
    bio: "Hello! My name is Ruby. I love feeling safe and having room to stretch my legs. I also love food and will prove it by dancing for you! <br> <br> I have arthritis and get meloxicam every day which I lap up like it’s candy. Because of my arthritis I need special litterbox accommodations, the area immediately surrounding my litterbox can be a little messy. The rest of my enclosure is very tidy though! <br> <br> I get along with my foster family and lounge next to my rabbit buddy in an enclosure next to mine. Because I wasn’t treated very well prior to rescue I have some trust issues and strangers make me a bit anxious. <br> <br> I would rather not be picked up. I need someone patient who will cherish me as I am and remind me that I am very special. It won’t be long before I will lay my velvety head on your foot and wait for you to pet me.",
  },

  {
    name: "Violet",
    image: "css/rabbitAssets/sanctuaryImages/Violet.png",
    breed: "Mini Rex",
    sex: "Female",
    age: "4 Years, 11 Months",
    weight: "6.4 Pounds",
    bio: "Poor Violet was set free to live on her own outdoors. By the time a neighbor spotted her, she'd been outside over the winter and spring had come. Violet is very wobbly with a presumed neurological condition. She was covered in ticks and really struggles to move around, with her wobbly, stiff walk. She falls over fairly frequently. <br> <br> Despite her troubles, Violet is SO SWEET. She loves to be petted and just craves attention. We were unable to diagnose the cause of her condition through blood tests and a visit to a neurologist. Violet was stable enough to be spayed, but does remain in need of special housing and care. Please help her with good wishes and support for her veterinary needs if you can! <br> <br> The best part of Violet's story is she is bonded to her best buddy Curly, another sanctuary rabbit. Violet and Curly cuddle all day and life is great if you ask them :)",
  },
];
